version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=cameo-bannister-pupil.ngrok-free.dev
      - WEBHOOK_URL=https://cameo-bannister-pupil.ngrok-free.dev
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.local/share/n8n

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=3EKbVgbTghgGl7gZu5byZuv5sHy_3Pun639vcjhfcbTa5gube
    command:
      - "http"
      - "n8n:5678"
      - "--domain=cameo-bannister-pupil.ngrok-free.dev"
    depends_on:
      - n8n

volumes:
  n8n_data: